# Generated by Django 4.2.8 on 2024-03-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weaklyevent_onetimeevent_daylyevent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DaylyEvent',
            new_name='DailyEvent',
        ),
        migrations.AlterField(
            model_name='weaklyevent',
            name='day',
            field=models.CharField(choices=[('MON', 'monday'), ('TUE', 'tuesday'), ('WED', 'wednesday'), ('THU', 'thursday'), ('FRI', 'friday'), ('SAT', 'saturday'), ('SUN', 'sunday')], default='MON', max_length=9),
        ),
    ]
