# Generated by Django 4.2.8 on 2024-04-06 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_goal_reached'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
