# Generated by Django 4.2.8 on 2024-04-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_weaklyevent_weeklyevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyevent',
            old_name='end',
            new_name='finish',
        ),
        migrations.RenameField(
            model_name='onetimeevent',
            old_name='end',
            new_name='finish',
        ),
        migrations.RenameField(
            model_name='weeklyevent',
            old_name='end',
            new_name='finish',
        ),
    ]
