# Generated by Django 4.2.8 on 2024-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_weeklyevent_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyevent',
            name='day',
            field=models.CharField(choices=[('MON', 'monday'), ('TUE', 'tuesday'), ('WED', 'wednesday'), ('THU', 'thursday'), ('FRI', 'friday'), ('SAT', 'saturday'), ('SUN', 'sunday')], default='MON', max_length=9),
        ),
    ]
